name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write  # Required for npm provenance attestation

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: https://registry.npmjs.org

      - run: npm ci

      - name: Publish
        run: npm publish --provenance

      - name: Version increment
        run: |
          # Push updated pakage.json version
          # so that we're ready to work on the next version
          npm version patch
          git commit -am "Patch version" || true
          git pull --rebase
          git push
